# Generated by Django 4.2.4 on 2023-08-30 04:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_place',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('note', models.TextField()),
                ('Payment', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
