# Generated by Django 4.2.4 on 2023-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='esewa',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
