# Generated by Django 4.2.4 on 2023-08-31 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_order_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_place',
            new_name='orderplace',
        ),
    ]
