# Generated by Django 4.2.4 on 2023-08-31 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_rename_order_place_orderplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplace',
            name='Payment',
        ),
    ]
